### ISSUE TITLE
REEDME 有笔误的地方

### ISSUE THREAD

**Issue by shineqstm** [venusic/E-signature#3]
>  <com.wastrel.handwrite.view.HandWriteView
>                android:id="@+id/view"
>                android:layout_width="match_parent"
>                app:paintMaxWidth="20px" //最大宽度
>                app:paintMinWidth="10px" //最小宽度
>                app:paintColor="#FF0000" //颜色
>                android:layout_height="match_parent"/>

这部分，路径错了，应该是下面这个
 <com.venusic.handwrite.view.HandWriteView
            android:id="@+id/view"
            android:layout_width="match_parent"
            app:paintMaxWidth="20px"
            app:paintMinWidth="10px"
            app:paintColor="#FF0000"
            android:layout_height="match_parent"/>
注意：com.wastrel.handwrite.view.HandWriteView 和 com.venusic.handwrite.view.HandWriteView

**Comment by venusic** [comment]
感谢，马上改。
